// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYzfZmCWi7AW0wIB7UBRrbIoDs0HHf8hI',
    appId: '1:234888009676:web:ebb1528c10f36718376f69',
    messagingSenderId: '234888009676',
    projectId: 'music-74001',
    authDomain: 'music-74001.firebaseapp.com',
    storageBucket: 'music-74001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuHhn7PlIUx50oRdXkUpDLEcIe7AfcUd4',
    appId: '1:234888009676:android:b06f685079143d33376f69',
    messagingSenderId: '234888009676',
    projectId: 'music-74001',
    storageBucket: 'music-74001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7BnK83Q2AuWB-79FTQ00M2NxiMPWWEDA',
    appId: '1:234888009676:ios:e155754cc5137f16376f69',
    messagingSenderId: '234888009676',
    projectId: 'music-74001',
    storageBucket: 'music-74001.firebasestorage.app',
    iosBundleId: 'com.example.youtubeMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7BnK83Q2AuWB-79FTQ00M2NxiMPWWEDA',
    appId: '1:234888009676:ios:e155754cc5137f16376f69',
    messagingSenderId: '234888009676',
    projectId: 'music-74001',
    storageBucket: 'music-74001.firebasestorage.app',
    iosBundleId: 'com.example.youtubeMusic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYzfZmCWi7AW0wIB7UBRrbIoDs0HHf8hI',
    appId: '1:234888009676:web:9b6991a8de66c928376f69',
    messagingSenderId: '234888009676',
    projectId: 'music-74001',
    authDomain: 'music-74001.firebaseapp.com',
    storageBucket: 'music-74001.firebasestorage.app',
  );
}
